### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by Sergio-Ka** [KatePronina/CV#13]
Сейчас в проекте подключены не все типы шрифтов наряду с woff и ttf должны быть еще svg шрифты.

**Comment by KatePronina** [comment]
Меня немного смущает пункт в стандартах о форматах шрифта, я не очень поняла, для чего нужен шрифт в svg?) Сейчас же у woff отличная поддержка, даже ttf можно убрать, woff и woff2 должно хватать
Или это для поддержки совсем старых версий браузеров типа IE8 и Safari 4?

**Comment by Sergio-Ka** [comment]
В том числе для поддержки совместимости думаю. Опять же векторные штуки бывают удобнее, так как можно влиять на их кишки. Хотя возможно в нынешних реалиях это уже становится не совсем актуально. Будет возможность поднять этот вопрос еще раз, когда будешь работать у нас. Возможно стоит пересмотреть этот момент.
