### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Sha1fei** [KatePronina/CV#5]
1) profile__description-important здесь лучше сделать модификатором к примеру theme_bold
2) В отдельных файлах нужно размещать блоки, а не элементы см.  skills__item, software__list-item, файл practice.pug

**Comment by Sha1fei** [comment]
Не используй миксы в блоке header) Вот тут описано почемуhttps://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_7mb9j/

**Comment by Sha1fei** [comment]
В header странные модификаторы, наверно ты хотела элементы там заюзать)) Не забудь убрать не нужные комменты)

**Comment by KatePronina** [comment]
Исправила модификаторы на элементы
Делала через модификаторы, т.к. в требованиях указано "осуществляются подобного рода кастомизации через добавление модификаторов к блоку", вот я и решила вынести изменяемые стили в модификаторы)
