### ISSUE TITLE
Проверить контент на длинные именования

### ISSUE THREAD

**Issue by Sha1fei** [KatePronina/CV#7]
Перенос поправила, но только в одном мест. Нужно проверить все резюме (заголовки) что не ломается верстка ( в том числе, появляются не нужные скроллы), при длинных именованиях.
![Screenshot 2019-08-20 at 10 54 23](https://user-images.githubusercontent.com/31854808/63316634-b93f5b00-c339-11e9-9e00-2ef5c61b3779.png)

**Comment by KatePronina** [comment]
Да, я везде смотрю обычно, тут проглядела, буду внимательнее)
